# Generated by Django 6.1.1 on 2026-09-09 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('remote', models.BooleanField(default=False)),
                ('url', models.URLField(max_length=1000)),
                ('description_raw', models.TextField(blank=True)),
                ('description_normalized', models.TextField(blank=True)),
                ('dedupe_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('fit_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fit_rationale', models.TextField(blank=True)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='job_sources.jobsource')),
            ],
            options={
                'ordering': ['-discovered_at'],
                'indexes': [models.Index(fields=['fit_score'], name='postings_jo_fit_sco_ca7908_idx'), models.Index(fields=['source', 'discovered_at'], name='postings_jo_source__a65aa5_idx')],
            },
        ),
    ]
