# Generated by Django 6.1.1 on 2026-09-09 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('postings', '0002_scoringlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('saved', 'Saved'), ('skipped', 'Skipped')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='postings.jobposting')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_decisions', to='accounts.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('posting', 'profile'), name='one_decision_per_profile_per_posting')],
            },
        ),
    ]
