# Generated by Django 6.0.8 on 2026-09-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_postingdecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='digested',
            field=models.BooleanField(default=False),
        ),
    ]
