# Generated by Django 6.0.8 on 2026-09-11 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('high_fit_job', 'High-fit job found'), ('application_advanced', 'Application advanced'), ('deadline_reminder', 'Deadline reminder'), ('source_poll_failed', 'Source poll failed'), ('weekly_digest', 'Weekly digest')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
