# Generated by Django 6.1.1 on 2026-09-09 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title_keywords', models.JSONField(blank=True, default=list)),
                ('excluded_keywords', models.JSONField(blank=True, default=list)),
                ('yoe_min', models.PositiveIntegerField(blank=True, null=True)),
                ('yoe_max', models.PositiveIntegerField(blank=True, null=True)),
                ('locations', models.JSONField(blank=True, default=list)),
                ('remote_ok', models.BooleanField(default=True)),
                ('salary_floor', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_profiles', to='accounts.profile')),
            ],
            options={
                'ordering': ['-active', 'name'],
            },
        ),
    ]
