# Generated by Django 6.1.1 on 2026-09-09 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('ashby', 'Ashby'), ('remoteok', 'RemoteOK'), ('rss', 'RSS'), ('manual_scrape', 'Manual scrape')], max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('poll_interval_minutes', models.PositiveIntegerField(default=120)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('is_auto_submit_eligible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_sources', to='accounts.profile')),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
    ]
