# Generated by Django 6.1.1 on 2026-09-09 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postings', '0002_scoringlog'),
        ('resumes', '0002_tailoredresume_tailoringlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('tailoring', 'Tailoring'), ('ready', 'Ready'), ('applied', 'Applied'), ('oa_interview', 'OA / Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('ghosted', 'Ghosted')], default='discovered', max_length=20)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('submission_method', models.CharField(blank=True, choices=[('api', 'API'), ('manual', 'Manual')], max_length=10, null=True)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='postings.jobposting')),
                ('tailored_resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='resumes.tailoredresume')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='applications.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('tailoring', 'Tailoring'), ('ready', 'Ready'), ('applied', 'Applied'), ('oa_interview', 'OA / Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('ghosted', 'Ghosted')], max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('gmail_auto', 'Gmail (auto-detected)')], default='manual', max_length=15)),
                ('confirmed', models.BooleanField(default=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='applications.application')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
