# Generated by Django 6.1.1 on 2026-09-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_tailoredresume_tailoringlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailoredresume',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
