# Generated by Django 6.1.1 on 2026-09-11 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('resumes', '0003_tailoredresume_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TailoringSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_title', models.CharField(blank=True, max_length=200)),
                ('style_notes', models.TextField(blank=True)),
                ('max_bullets_per_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('max_bullets_per_project', models.PositiveIntegerField(blank=True, null=True)),
                ('avoid_em_dash', models.BooleanField(default=True)),
                ('exclude_company_name_from_body', models.BooleanField(default=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tailoring_settings', to='accounts.profile')),
            ],
        ),
    ]
